FROM apache/superset:latest

USER root

# 시스템 패키지 설치 (드라이버 설치 오류 방지)
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    gcc && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# PostgreSQL 드라이버 및 유틸 설치
RUN pip install --no-cache-dir psycopg2-binary sqlalchemy sqlalchemy-utils

USER superset
