version: "3.9"

services:
  db:
    image: postgres:16.0
    container_name: capstone-db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app_pw
      POSTGRES_DB: appdb
      TZ: Asia/Seoul
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # ✅ 초기 스크립트 자동 실행
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d appdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    image: capstone/backend:latest
    container_name: capstone-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://app:app_pw@db:5432/appdb
      TZ: Asia/Seoul
    ports:
      - "8000:8000"

  backup:
    image: postgres:16.0
    container_name: capstone-db-backup
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app_pw
      POSTGRES_DB: appdb
      POSTGRES_HOST: db
      TZ: Asia/Seoul
    volumes:
      - ./backup:/backup
      - ./backup.sh:/docker-entrypoint-initdb.d/backup.sh
    command: ["bash", "/docker-entrypoint-initdb.d/backup.sh"]

  superset:
    build:
      context: .
      dockerfile: Dockerfile.superset
    container_name: capstone-superset
    ports:
      - "8088:8088"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SUPERSET_SECRET_KEY: "capstone-secret-key"
      ADMIN_USERNAME: admin
      ADMIN_FIRSTNAME: Admin
      ADMIN_LASTNAME: User
      ADMIN_EMAIL: admin@superset.com
      ADMIN_PASSWORD: admin
      TZ: Asia/Seoul
    volumes:
      - superset_data:/app/superset_home
    command: >
      /bin/bash -c "
        superset db upgrade &&
        superset fab create-admin --username ${ADMIN_USERNAME} --firstname ${ADMIN_FIRSTNAME} --lastname ${ADMIN_LASTNAME} --email ${ADMIN_EMAIL} --password ${ADMIN_PASSWORD} &&
        superset init &&
        superset run -h 0.0.0.0 -p 8088"
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: capstone-pgadmin
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: gkstntjd486
      TZ: Asia/Seoul
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped

volumes:
  superset_data:
  pgadmin_data:
