version: "3.9"

services:
  db:
    image: postgres:16.0
    container_name: capstone-db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app_pw
      POSTGRES_DB: appdb
      TZ: Asia/Seoul
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d appdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    image: capstone/backend:latest
    container_name: capstone-backend
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      TZ: Asia/Seoul
    ports:
      - "8000:8000"
    restart: always

  superset:
    build:
      context: .
      dockerfile: Dockerfile.superset
    container_name: capstone-superset
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8088:8088"
    env_file:
      - .env
    volumes:
      - superset_data:/app/superset_home
    command: >
      /bin/bash -c "
        superset db upgrade &&
        superset fab create-admin --username ${ADMIN_USERNAME} --firstname ${ADMIN_FIRSTNAME} --lastname ${ADMIN_LASTNAME} --email ${ADMIN_EMAIL} --password ${ADMIN_PASSWORD} || true &&
        superset init &&
        superset run -h 0.0.0.0 -p 8088
      "
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: capstone-pgadmin
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "gkstntjd486"
      TZ: Asia/Seoul
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped

volumes:
  superset_data:
  pgadmin_data:
